// GENERATED by tools/build-app.mjs from app/src/tasks.jsx — do not edit.
// Edit the source and rebuild:  node tools/build-app.mjs tasks
function __app() {   // line 4 here is line 1 of the .jsx
// tasks.jsx — a checklist, and the worked example for the component runtime.
//
// Build it before pushing (app/apps/tasks.js is generated, not edited):
//
//   node tools/build-app.mjs tasks
//   .\push.ps1 app\apps\tasks.js
//
// It is here to show the parts of the model that a counter would not:
//
//   Done items sink to the bottom, so every toggle reorders the list. The rows
//   carry keys, so the widgets move rather than being rebuilt — the case an
//   imperative version has to handle by deleting every row and making new ones,
//   which is also the case where deleting the row LVGL is dispatching to would
//   bite. Renders are batched into a microtask, so it cannot.
//
//   The confirm panel replaces the screen's contents from inside a click
//   handler, with none of the lv.timer(20) deferral apps/wifi.js needs.
//
//   Nothing here calls .clean(), .delete(), or .set(). The tree is the whole
//   description of the screen, and everything else is the runtime's problem.

const STORE = "/tasks.json";

const SEED = [
  { id: 1, text: "Flash the firmware", done: true },
  { id: 2, text: "Push an app", done: true },
  { id: 3, text: "Write one in JSX", done: false },
  { id: 4, text: "Reorder without a rebuild", done: false },
  { id: 5, text: "Read docs/ui-runtime.md", done: false },
];

function load() {
  if (!fs.available()) return SEED;
  try {
    const raw = fs.read(STORE);
    if (!raw) return SEED;
    const items = JSON.parse(raw);
    return Array.isArray(items) && items.length ? items : SEED;
  } catch (e) {
    console.error("tasks: could not read " + STORE + ":", e);
    return SEED;
  }
}

function save(items) {
  if (!fs.available()) return;
  fs.write(STORE, JSON.stringify(items));
}

const S = lv.size();
// The firmware's corner button is 34px in the bottom-right; leave it clear.
const CORNER = 40;
const HEADER = 34;
const FOOTER = 38;

const INK = "#F0F4F8";
const DIM = "#64798C";
const CARD = "#101E2C";

function Header({ done, total }) {
  return (
    h("obj", {w: "100%", h: HEADER, bg: "#0B1622", border: 0, pad: 0, radius: 0, scroll: false,
align: "top-mid", y: 0},
h("label", {align: "left-mid", x: 10, font: 20, color: INK, text: "Tasks"}),
h("label", {align: "right-mid", x: -10, font: 14, color: DIM, text: done + "/" + total + " done"}))

  );
}

function TaskRow({ task, onToggle }) {
  // A row is a list button, so its widget comes from the list rather than from
  // lv.button(); that is the whole difference, and the key is what lets it be
  // moved instead of rebuilt when this task sinks past the others.
  return (
    h("row", {key: task.id,
text: (task.done ? "✓  " : "·  ") + task.text,
color: task.done ? DIM : INK,
onClick: () => onToggle(task.id)})
  );
}

function Confirm({ count, onYes, onNo }) {
  return (
    h("obj", {w: "88%", h: "content", align: "center", bg: CARD, border: 1, borderColor: "#2A4258",
radius: 10, pad: 12, flex: "column", flexAlign: ["center", "center"], scroll: false},
h("label", {w: "100%", font: 16, color: INK, text: "Clear " + count + " done?"}),
h("obj", {w: "100%", h: "content", bg: CARD, border: 0, pad: 0, radius: 0, scroll: false,
flex: "row", flexAlign: ["evenly", "center"]},
h("button", {w: 64, h: 34, bg: "#1D3A57", color: INK, text: "Clear", onClick: onYes}),
h("button", {w: 64, h: 34, bg: "#22303E", color: INK, text: "Keep", onClick: onNo}))
)

  );
}

function App() {
  const [items, setItems] = useState(load);
  const [asking, setAsking] = useState(false);

  // Undone first, and stable within each group, so a toggle moves exactly one
  // row. The list this returns is what the reconciler diffs against the last
  // one; the keys are what make the difference a move.
  const ordered = useMemo(
    () => [...items].sort((a, b) => (a.done ? 1 : 0) - (b.done ? 1 : 0)),
    [items],
  );
  const done = items.filter(t => t.done).length;

  // Writing to storage is a side effect of the list changing, not of the tap
  // that changed it — so it happens once per change however the change arrived.
  useEffect(() => { save(items); }, [items]);

  const toggle = id =>
    setItems(items.map(t => (t.id === id ? { ...t, done: !t.done } : t)));

  return (
    h(Fragment, {},
h(Header, {done: done, total: items.length}),

h("list", {w: S.w - 12, h: S.h - HEADER - FOOTER, align: "top-mid", y: HEADER,
bg: CARD, border: 0, radius: 8},
ordered.map(task => h(TaskRow, {key: task.id, task: task, onToggle: toggle})))
,

!asking && done > 0 && (
        h("button", {w: 92, h: 30, align: "bottom-left", x: 8, y: -4, bg: "#22303E", color: INK,
font: 14, text: "Clear done", onClick: () => setAsking(true)})
      ),

asking && (
        h(Confirm, {
count: done,
onYes: () => { setItems(items.filter(t => !t.done)); setAsking(false); },
onNo: () => setAsking(false)})

      ))

  );
}

lv.screen().set({ bg: "#0B1622" });
render(h(App, {}));
}
const {h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval} = (function () {
const HOST_TAGS = ["obj", "button", "label", "slider", "switch", "arc", "list", "chart", "tabview", "textarea", "keyboard"]; const PARENT_MADE = { row: "list", tab: "tabview" };
const FIXED_ORDER = { tabview: true }; const TEXT_PROP = { label: true, button: true, row: true }; const EVENTS = {
onClick: "click", onChange: "change", onPress: "press", onPressing: "pressing", onLongPress: "longpress", onReady: "ready", onCancel: "cancel", };
const CREATE_ONLY = { seriesColor: true, name: true }; const RESET = { hidden: false, text: "", scroll: true, clickable: true };
const NOT_A_PROP = { key: true, ref: true, children: true }; function h(type, props, ...kids) { const p = {}; for (const k in props) p[k] = props[k];
if (kids.length) p.children = kids.length === 1 ? kids[0] : kids; return { type, key: p.key === undefined || p.key === null ? null : String(p.key), props: p,
kids: flatten(p.children), }; } function Fragment(props) { return props.children; } function flatten(kids, out) { out = out || [];
if (kids === undefined || kids === null || kids === false || kids === true) return out; if (Array.isArray(kids)) { for (const k of kids) flatten(k, out); return out; }
out.push(kids); return out; } const isText = v => typeof v === "string" || typeof v === "number"; let current = null; let hookAt = 0; function slot(init) {
if (!current) throw new Error("hooks can only be called while a component renders"); const hooks = current.hooks; if (hooks.length <= hookAt) hooks.push(init());
return hooks[hookAt++]; } function useState(initial) { const inst = current; const cell = slot(() => { const c = { v: typeof initial === "function" ? initial() : initial };
c.set = next => { const v = typeof next === "function" ? next(c.v) : next; if (Object.is(v, c.v)) return; c.v = v; invalidate(inst); }; return c; }); return [cell.v, cell.set]; }
function useRef(initial) { return slot(() => ({ current: initial })); } function useMemo(fn, deps) { const s = slot(() => ({ deps: null, v: undefined, first: true }));
if (s.first || !sameDeps(s.deps, deps)) { s.v = fn(); s.deps = deps; s.first = false; } return s.v; } function useCallback(fn, deps) { return useMemo(() => fn, deps); }
function useEffect(fn, deps) { const inst = current; const s = slot(() => ({ deps: null, cleanup: null, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.deps = deps;
s.first = false; inst.pending.push(s, fn); } } function useInterval(fn, ms) { const held = useRef(fn); held.current = fn; useEffect(() => {
if (ms === null || ms === undefined || ms === false) return undefined; const t = lv.timer(ms, () => held.current()); return () => t.stop(); }, [ms]); } function sameDeps(a, b) {
if (!a || !b || a.length !== b.length) return false; for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } const dirty = [];
const effectQueue = []; let scheduled = false; let chain = 0; function invalidate(inst) { if (inst.gone || inst.dirty) return; inst.dirty = true; dirty.push(inst); schedule(); }
function schedule() { if (scheduled) return; scheduled = true; Promise.resolve().then(flush); } function flush() { scheduled = false; if (++chain > 40) { chain = 0;
dirty.length = 0; effectQueue.length = 0; console.error("[ui] runaway render: a component sets state on every render, stopping"); return; } while (dirty.length) {
const inst = dirty.shift(); if (!inst.dirty || inst.gone) continue; inst.dirty = false; try { renderComponent(inst); } catch (e) {
console.error("[ui] <" + (inst.fn.name || "anonymous") + "> failed to render:", e); } } runEffects(); if (!scheduled) chain = 0; } function runEffects() {
while (effectQueue.length) { const inst = effectQueue.shift(); const pending = inst.pending; inst.pending = []; for (let i = 0; i < pending.length; i += 2) { if (inst.gone) break;
const s = pending[i], fn = pending[i + 1]; if (s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } const r = safely(fn, "effect");
s.cleanup = typeof r === "function" ? r : null; } } } function safely(fn, what) { try { return fn(); } catch (e) { console.error("[ui] " + what + " threw:", e); return null; } }
function mount(vnode, box, owner) { if (isText(vnode)) { const inst = mountHost(h("label", { text: String(vnode) }), box, owner); inst.autoLabel = true; return inst; }
if (typeof vnode.type === "function") { const inst = { kind: "comp", vnode, fn: vnode.type, key: vnode.key, hooks: [],
pending: [], kids: [], box, owner, dirty: false, mounted: false, gone: false }; renderComponent(inst); return inst; } return mountHost(vnode, box, owner); }
function mountHost(vnode, box, owner) { const tag = vnode.type; const props = vnode.props; const inst = { kind: "host", vnode, key: vnode.key, tag, box, owner,
kids: [], handlers: {}, bound: {}, autoLabel: false, gone: false }; const create = {}; for (const k in props) { if (NOT_A_PROP[k] || EVENTS[k]) continue; create[k] = props[k]; }
const text = textOf(vnode); if (text !== null) create.text = text; if (PARENT_MADE[tag]) { if (!owner || owner.tag !== PARENT_MADE[tag])
throw new Error("<" + tag + "> must be a direct child of <" + PARENT_MADE[tag] + ">"); if (tag === "row") { inst.w = owner.w.add(create.text || ""); delete create.text; } else {
inst.w = owner.w.addTab(String(props.name || "")); delete create.name; } if (Object.keys(create).length) inst.w.set(create); } else {
if (HOST_TAGS.indexOf(tag) < 0) throw new Error("unknown element <" + tag + ">"); inst.w = lv[tag](box, create); } bindEvents(inst, props); setRef(props.ref, inst.w);
if (text === null) inst.kids = mountKids(vnode.kids, inst.w, inst); return inst; } function mountKids(kids, box, owner) { const out = [];
for (const k of kids) out.push(mount(k, box, owner)); return out; } function renderComponent(inst) { const prevInst = current, prevHook = hookAt; current = inst; hookAt = 0;
let out; try { out = inst.fn(inst.vnode.props); } finally { current = prevInst; hookAt = prevHook; } const kids = flatten(out); if (inst.mounted) { diffKids(inst, kids); } else {
inst.mounted = true; inst.kids = mountKids(kids, inst.box, inst.owner); } if (inst.pending.length) effectQueue.push(inst); } function unmount(inst) { inst.gone = true;
if (inst.kind === "comp") { for (const s of inst.hooks) { if (s && s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } } inst.pending.length = 0; }
for (const k of inst.kids) unmount(k); if (inst.kind === "host") { setRef(inst.vnode.props.ref, null); inst.w.delete(); } } function setRef(ref, value) { if (!ref) return;
if (typeof ref === "function") safely(() => ref(value), "ref"); else ref.current = value; } function bindEvents(inst, props) { for (const prop in EVENTS) {
if (typeof props[prop] !== "function") continue; inst.handlers[prop] = props[prop]; if (inst.bound[prop]) continue; inst.bound[prop] = true; const name = EVENTS[prop];
inst.w.on(name, (w, x, y) => { const fn = inst.handlers[prop]; if (!fn) return; const e = { target: w, type: name, x, y }; if (name === "change") e.value = w.value(); fn(e); }); }
} function updateEvents(inst, props) { for (const prop in EVENTS) { const fn = props[prop]; inst.handlers[prop] = typeof fn === "function" ? fn : null; } bindEvents(inst, props); }
function textOf(vnode) { if (!TEXT_PROP[vnode.type]) return null; if (vnode.props.text !== undefined) return String(vnode.props.text); if (!vnode.kids.length) return null;
if (!vnode.kids.every(isText)) return null; return vnode.kids.join(""); } function diffProps(inst, oldVnode, newVnode) { const oldProps = oldVnode.props, newProps = newVnode.props;
const patchProps = {}; let any = false; for (const k in newProps) { if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue;
if (!eq(newProps[k], oldProps[k])) { patchProps[k] = newProps[k]; any = true; } } for (const k in oldProps) {
if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue; if (k in newProps || !(k in RESET)) continue; patchProps[k] = RESET[k]; any = true; }
const oldText = textOf(oldVnode), newText = textOf(newVnode); if (newText !== null && newText !== oldText) { patchProps.text = newText; any = true; }
else if (newText === null && oldText !== null) { patchProps.text = RESET.text; any = true; } if (any) inst.w.set(patchProps); } function eq(a, b) {
if (Object.is(a, b)) return true; if (Array.isArray(a) && Array.isArray(b)) { if (a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } return false; } function compatible(inst, vnode) {
if (isText(vnode)) return inst.kind === "host" && inst.autoLabel; if (vnode.key !== inst.key) return false;
if (typeof vnode.type === "function") return inst.kind === "comp" && inst.fn === vnode.type; if (inst.kind !== "host" || inst.tag !== vnode.type || inst.autoLabel) return false;
if (FIXED_ORDER[vnode.type]) return sameTabs(inst.vnode.kids, vnode.kids); if (inst.tag === "tab") return String(inst.vnode.props.name || "") === String(vnode.props.name || "");
return true; } function sameTabs(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) { const x = a[i], y = b[i];
if (isText(x) || isText(y) || x.type !== y.type) return false; if (x.type === "tab" && String(x.props.name || "") !== String(y.props.name || "")) return false; } return true; }
function patch(inst, vnode) { if (isText(vnode)) vnode = h("label", { text: String(vnode) }); if (inst.kind === "comp") { inst.vnode = vnode; inst.dirty = false;
renderComponent(inst); return inst; } const oldVnode = inst.vnode; inst.vnode = vnode; diffProps(inst, oldVnode, vnode); updateEvents(inst, vnode.props);
if (oldVnode.props.ref !== vnode.props.ref) { setRef(oldVnode.props.ref, null); setRef(vnode.props.ref, inst.w); } if (textOf(vnode) === null) diffKids(inst, vnode.kids);
return inst; } function diffKids(ownerInst, newKids) { const old = ownerInst.kids; const box = ownerInst.kind === "host" ? ownerInst.w : ownerInst.box;
const owner = ownerInst.kind === "host" ? ownerInst : ownerInst.owner; const keyed = old.some(i => i.key !== null) || newKids.some(v => !isText(v) && v.key !== null);
const next = []; let structural = false; if (!keyed) { for (let i = 0; i < newKids.length; i++) { const o = old[i]; if (o && compatible(o, newKids[i])) {
next.push(patch(o, newKids[i])); } else { if (o) unmount(o); next.push(mount(newKids[i], box, owner)); structural = true; } }
for (let i = newKids.length; i < old.length; i++) { unmount(old[i]); structural = true; } } else { const pool = new Map(); for (const o of old) { if (o.key === null) continue;
const type = tagOf(o); let byKey = pool.get(type); if (!byKey) pool.set(type, byKey = new Map()); byKey.set(o.key, o); } const reused = new Set(); let unkeyedAt = 0;
for (const v of newKids) { const key = isText(v) ? null : v.key; let o = null; if (key !== null) { const byKey = pool.get(typeOf(v)); o = (byKey && byKey.get(key)) || null;
} else { while (unkeyedAt < old.length && old[unkeyedAt].key !== null) unkeyedAt++; o = old[unkeyedAt] || null; unkeyedAt++; } if (o && !reused.has(o) && compatible(o, v)) {
reused.add(o); next.push(patch(o, v)); } else { next.push(mount(v, box, owner)); structural = true; } } for (const o of old) {
if (!reused.has(o)) { unmount(o); structural = true; } } if (!structural) { for (let i = 0; i < next.length; i++) { if (next[i] !== old[i]) { structural = true; break; } } } }
ownerInst.kids = next; if (structural && owner && !FIXED_ORDER[owner.tag]) reorder(owner, box); } function tagOf(inst) { return inst.kind === "comp" ? inst.fn : inst.tag; }
function typeOf(vnode) { return isText(vnode) ? "label" : vnode.type; } function reorder(owner, box) { const widgets = []; collect(owner, widgets, box);
for (let i = 0; i < widgets.length; i++) { if (widgets[i].index() !== i) widgets[i].index(i); } } function collect(inst, out, box) { for (const k of inst.kids) {
if (k.kind === "host") { if (k.box === box) out.push(k.w); } else { collect(k, out, box); } } } function render(tree, parent) { const box = parent || lv.screen(); box.clean();
const root = { kind: "frag", key: null, vnode: null, kids: [], box, owner: null, gone: false }; root.owner = root; root.kids = mountKids(flatten(tree), box, root);
reorder(root, box); runEffects(); return { update(next) { diffKids(root, flatten(next)); runEffects(); }, unmount() { for (const k of root.kids) unmount(k); root.kids = []; }, }; }
const UI = { h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval };
return UI; })();
__app();
