// GENERATED by tools/build-app.mjs from app/src/vitals.jsx — do not edit.
// Edit the source and rebuild:  node tools/build-app.mjs vitals
function __app() {   // line 4 here is line 1 of the .jsx
// vitals.jsx — the 4-tab dashboard, as components.
//
// A port of the imperative app/apps/vitals.js, kept behaviour-for-behaviour the
// same so the two can be compared: same tabs, same layout arithmetic, same
// 500 ms readout cycle, same wifi scan, same touch dot. The imperative original
// is in this repo's history at the commit that replaced it, and weather.js and
// wifi.js are still written that way.
//
// It is the honest comparison rather than the flattering one, because two parts
// of this app are *not* what a reconciler is good at, and both are called out
// below: the arc that has to measure its parent before it can size itself, and
// the dot that follows a finger. Everything else got shorter.

const S = lv.size();
const BAR_H = 30;
const TAB_H = S.h - BAR_H - 8;   // content height inside a tab, past pad: 4

const CYAN = "#00BCD4";

// ---------------------------------------------------------------- tab 1: Vitals

function VitalsTab({ heap, load, uptime, battery, chartRef }) {
  // The arc has to stay square and fit the column it is in, and the column's
  // real width is only knowable after a layout pass — 40% of the tab is not what
  // is left once padding and the theme's card border have taken theirs. The
  // imperative version reads bounds() at construction time, which it can,
  // because by then the parent exists.
  //
  // Declaratively it takes two passes: render with the estimate the original
  // used as its fallback, measure in an effect, and correct. The correction is
  // one .set() on one widget, on the first frame, and this is the clearest case
  // in the app where the imperative version is simply more direct.
  const right = useRef(null);
  const [arc, setArc] = useState(Math.min((S.w * 0.3) | 0, (TAB_H * 0.6) | 0));
  useEffect(() => {
    const w = right.current.bounds().w;
    if (w) setArc(Math.min(w, (TAB_H * 0.6) | 0));
  }, []);

  return (
    h("tab", {name: "Vitals", pad: 4, scroll: false},
h("obj", {w: "58%", h: "100%", align: "left-mid", pad: 4, scroll: false},
h("label", {align: "top-left", font: 14, text: heap}),
h("chart", {
ref: chartRef,
w: "100%", h: "70%", align: "bottom-mid",


points: Math.max(20, (S.w / 8) | 0),
range: [0, 340], divs: [4, 6], seriesColor: CYAN})
)
,

h("obj", {ref: right, w: "40%", h: "100%", align: "right-mid", pad: 4, scroll: false},
h("arc", {w: arc, h: arc, align: "top-mid",
range: [0, 100], rotation: 135, angles: [0, 270], knob: false,
value: load},
h("label", {align: "center", font: 16, text: load + "%"}))
,
h("label", {align: "bottom-mid", font: 14, text: uptime + "  " + battery}))
)

  );
}

// ---------------------------------------------------------------- tab 2: Touch

function TouchTab() {
  // The dot follows a finger, which is the one thing in this app that the docs
  // say not to put through the reconciler: a render per pointer move, to move
  // one widget, while the other three tabs are diffed for nothing. So it is a
  // ref and two .set() calls, exactly as the imperative version does it — the
  // escape hatch is there to be used, and this is what it is for.
  const dot = useRef(null);
  const box = useRef(null);
  const coords = useRef(null);

  const follow = e => {
    const b = box.current.bounds();
    dot.current.set({ x: e.x - b.x - 5, y: e.y - b.y - 5, hidden: false });
    coords.current.set({ text: `x ${e.x}  y ${e.y}` });
  };

  return (
    h("tab", {name: "Touch", pad: 4, scroll: false},
h("label", {ref: coords, align: "top-left", x: 2, y: 0, font: 14, text: "touch the box"}),
h("obj", {ref: box,

w: "100%", h: TAB_H - 22, align: "bottom-mid", y: -2,
bg: "#11202B", border: 1, borderColor: CYAN, scroll: false, clickable: true,
onPress: follow, onPressing: follow},
h("obj", {ref: dot, w: 10, h: 10, radius: 5, bg: "#FFC107", border: 0, hidden: true}))
)

  );
}

// ---------------------------------------------------------------- tab 3: WiFi

function WifiTab() {
  const [status, setStatus] = useState("idle");
  const [nets, setNets] = useState([]);

  const SCAN_W = 84;

  const scan = () => {
    const started = wifi.scan(found => {
      if (!found) { setStatus("scan failed"); setNets([]); return; }
      setStatus(found.length + " found");
      setNets(found.slice(0, 12));
    });
    if (started) {
      setNets([]);
      setStatus("scanning...");
    }
  };

  return (
    h("tab", {name: "WiFi", pad: 4, scroll: false},
h("button", {w: SCAN_W, h: 30, align: "top-left", text: "Scan", onClick: scan}),
h("label", {align: "top-left", x: SCAN_W + 8, y: 8, font: 14, text: status}),

h("list", {w: S.w - 48, h: TAB_H - 36, align: "bottom-left"},
nets.map(n => (
          h("row", {key: n.ssid + " " + n.rssi, text: `${n.ssid}  ${n.rssi}dBm`})
        )))
)

  );
}

// ---------------------------------------------------------------- tab 4: System

function SystemTab({ fps }) {
  const i = useMemo(() => sys.info(), []);
  return (
    h("tab", {name: "System", pad: 4, scroll: false},
h("label", {align: "top-left", x: 2, y: 0, font: 14,
text: `${i.model}  rev${i.rev}  ${i.cores}x${i.mhz}MHz\n` +
                   `flash ${i.flashMB}MB   psram ${i.psramMB}MB   lvgl ${i.lvgl}   qjs ${i.quickjs}`}),
h("label", {align: "top-right", x: -2, y: 34, font: 16, color: CYAN, text: fps + " fps"}),
h("label", {align: "bottom-left", x: 2, y: -34, font: 14, text: "backlight"}),
h("slider", {w: "90%", h: 14, align: "bottom-mid", y: -8, range: [5, 100], value: 80,
onChange: e => sys.backlight(e.value)}))

  );
}

// ---------------------------------------------------------------- the dashboard

function Dashboard() {
  const chart = useRef(null);
  const [live, setLive] = useState({
    heap: "heap --", load: 0, uptime: "up 0s", battery: "", fps: 0,
  });

  // One timer for every readout, as the original has. Each pass writes one
  // object, so one state write re-renders the tree once; useState's bail-out
  // means a value that has not moved costs nothing further down.
  useInterval(() => {
    const h = sys.heap();
    const fps = sys.fps();
    const up = (sys.uptime() / 1000) | 0;
    const bat = sys.battery();

    chart.current.push((h.internal / 1024) | 0);

    setLive({
      heap: `heap ${(h.internal / 1024) | 0} kB  psram ${(h.psram / 1024) | 0} kB`,
      // Render throughput as a fraction of a 30 flush/s target, same as the C demo.
      load: Math.min(100, ((fps * 100) / 30) | 0),
      uptime: `up ${(up / 60) | 0}m ${up % 60}s`,
      battery: bat === null ? "bat n/a" : bat.toFixed(2) + "V",
      fps,
    });
  }, 500);

  return (
    h("tabview", {bar: BAR_H, bg: "#0A1520"},
h(VitalsTab, {heap: live.heap, load: live.load, uptime: live.uptime,
battery: live.battery, chartRef: chart}),
h(TouchTab, {}),
h(WifiTab, {}),
h(SystemTab, {fps: live.fps}))

  );
}

lv.screen().set({ bg: "#0A1520" });
render(h(Dashboard, {}));

console.log("vitals: dashboard up (4 tabs)");
}
const {h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval} = (function () {
const HOST_TAGS = ["obj", "button", "label", "slider", "switch", "arc", "list", "chart", "tabview", "textarea", "keyboard", "bar", "checkbox",
"roller", "dropdown", "spinner", "led"]; const PARENT_MADE = { row: "list", tab: "tabview" }; const FIXED_ORDER = { tabview: true };
const TEXT_PROP = { label: true, button: true, row: true, checkbox: true }; const EVENTS = { onClick: "click", onChange: "change", onPress: "press", onPressing: "pressing",
onLongPress: "longpress", onReady: "ready", onCancel: "cancel", }; const CREATE_ONLY = { seriesColor: true, name: true };
const RESET = { hidden: false, text: "", scroll: true, clickable: true }; const NOT_A_PROP = { key: true, ref: true, children: true }; function h(type, props, ...kids) {
const p = {}; for (const k in props) p[k] = props[k]; if (kids.length) p.children = kids.length === 1 ? kids[0] : kids; return { type,
key: p.key === undefined || p.key === null ? null : String(p.key), props: p, kids: flatten(p.children), }; } function Fragment(props) { return props.children; }
function flatten(kids, out) { out = out || []; if (kids === undefined || kids === null || kids === false || kids === true) return out; if (Array.isArray(kids)) {
for (const k of kids) flatten(k, out); return out; } out.push(kids); return out; } const isText = v => typeof v === "string" || typeof v === "number"; let current = null;
let hookAt = 0; function slot(init) { if (!current) throw new Error("hooks can only be called while a component renders"); const hooks = current.hooks;
if (hooks.length <= hookAt) hooks.push(init()); return hooks[hookAt++]; } function useState(initial) { const inst = current; const cell = slot(() => {
const c = { v: typeof initial === "function" ? initial() : initial }; c.set = next => { const v = typeof next === "function" ? next(c.v) : next; if (Object.is(v, c.v)) return;
c.v = v; invalidate(inst); }; return c; }); return [cell.v, cell.set]; } function useRef(initial) { return slot(() => ({ current: initial })); } function useMemo(fn, deps) {
const s = slot(() => ({ deps: null, v: undefined, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.v = fn(); s.deps = deps; s.first = false; } return s.v; }
function useCallback(fn, deps) { return useMemo(() => fn, deps); } function useEffect(fn, deps) { const inst = current;
const s = slot(() => ({ deps: null, cleanup: null, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.deps = deps; s.first = false; inst.pending.push(s, fn); } }
function useInterval(fn, ms) { const held = useRef(fn); held.current = fn; useEffect(() => { if (ms === null || ms === undefined || ms === false) return undefined;
const t = lv.timer(ms, () => held.current()); return () => t.stop(); }, [ms]); } function sameDeps(a, b) { if (!a || !b || a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } const dirty = []; const effectQueue = []; let scheduled = false; let chain = 0;
function invalidate(inst) { if (inst.gone || inst.dirty) return; inst.dirty = true; dirty.push(inst); schedule(); } function schedule() { if (scheduled) return; scheduled = true;
Promise.resolve().then(flush); } function flush() { scheduled = false; if (++chain > 40) { chain = 0; dirty.length = 0; effectQueue.length = 0;
console.error("[ui] runaway render: a component sets state on every render, stopping"); return; } while (dirty.length) { const inst = dirty.shift();
if (!inst.dirty || inst.gone) continue; inst.dirty = false; try { renderComponent(inst); } catch (e) {
console.error("[ui] <" + (inst.fn.name || "anonymous") + "> failed to render:", e); } } runEffects(); if (!scheduled) chain = 0; } function runEffects() {
while (effectQueue.length) { const inst = effectQueue.shift(); const pending = inst.pending; inst.pending = []; for (let i = 0; i < pending.length; i += 2) { if (inst.gone) break;
const s = pending[i], fn = pending[i + 1]; if (s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } const r = safely(fn, "effect");
s.cleanup = typeof r === "function" ? r : null; } } } function safely(fn, what) { try { return fn(); } catch (e) { console.error("[ui] " + what + " threw:", e); return null; } }
function mount(vnode, box, owner) { if (isText(vnode)) { const inst = mountHost(h("label", { text: String(vnode) }), box, owner); inst.autoLabel = true; return inst; }
if (typeof vnode.type === "function") { const inst = { kind: "comp", vnode, fn: vnode.type, key: vnode.key, hooks: [],
pending: [], kids: [], box, owner, dirty: false, mounted: false, gone: false }; renderComponent(inst); return inst; } return mountHost(vnode, box, owner); }
function mountHost(vnode, box, owner) { const tag = vnode.type; const props = vnode.props; const inst = { kind: "host", vnode, key: vnode.key, tag, box, owner,
kids: [], handlers: {}, bound: {}, autoLabel: false, gone: false }; const create = {}; for (const k in props) { if (NOT_A_PROP[k] || EVENTS[k]) continue; create[k] = props[k]; }
const text = textOf(vnode); if (text !== null) create.text = text; if (PARENT_MADE[tag]) { if (!owner || owner.tag !== PARENT_MADE[tag])
throw new Error("<" + tag + "> must be a direct child of <" + PARENT_MADE[tag] + ">"); if (tag === "row") { inst.w = owner.w.add(create.text || ""); delete create.text; } else {
inst.w = owner.w.addTab(String(props.name || "")); delete create.name; } if (Object.keys(create).length) inst.w.set(create); } else {
if (HOST_TAGS.indexOf(tag) < 0) throw new Error("unknown element <" + tag + ">"); inst.w = lv[tag](box, create); } bindEvents(inst, props); setRef(props.ref, inst.w);
if (text === null) inst.kids = mountKids(vnode.kids, inst.w, inst); return inst; } function mountKids(kids, box, owner) { const out = [];
for (const k of kids) out.push(mount(k, box, owner)); return out; } function renderComponent(inst) { const prevInst = current, prevHook = hookAt; current = inst; hookAt = 0;
let out; try { out = inst.fn(inst.vnode.props); } finally { current = prevInst; hookAt = prevHook; } const kids = flatten(out); if (inst.mounted) { diffKids(inst, kids); } else {
inst.mounted = true; inst.kids = mountKids(kids, inst.box, inst.owner); } if (inst.pending.length) effectQueue.push(inst); } function unmount(inst) { inst.gone = true;
if (inst.kind === "comp") { for (const s of inst.hooks) { if (s && s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } } inst.pending.length = 0; }
for (const k of inst.kids) unmount(k); if (inst.kind === "host") { setRef(inst.vnode.props.ref, null); inst.w.delete(); } } function setRef(ref, value) { if (!ref) return;
if (typeof ref === "function") safely(() => ref(value), "ref"); else ref.current = value; } function bindEvents(inst, props) { for (const prop in EVENTS) {
if (typeof props[prop] !== "function") continue; inst.handlers[prop] = props[prop]; if (inst.bound[prop]) continue; inst.bound[prop] = true; const name = EVENTS[prop];
inst.w.on(name, (w, x, y) => { const fn = inst.handlers[prop]; if (!fn) return; const e = { target: w, type: name, x, y }; if (name === "change") e.value = w.value(); fn(e); }); }
} function updateEvents(inst, props) { for (const prop in EVENTS) { const fn = props[prop]; inst.handlers[prop] = typeof fn === "function" ? fn : null; } bindEvents(inst, props); }
function textOf(vnode) { if (!TEXT_PROP[vnode.type]) return null; if (vnode.props.text !== undefined) return String(vnode.props.text); if (!vnode.kids.length) return null;
if (!vnode.kids.every(isText)) return null; return vnode.kids.join(""); } function diffProps(inst, oldVnode, newVnode) { const oldProps = oldVnode.props, newProps = newVnode.props;
const patchProps = {}; let any = false; for (const k in newProps) { if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue;
if (!eq(newProps[k], oldProps[k])) { patchProps[k] = newProps[k]; any = true; } } for (const k in oldProps) {
if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue; if (k in newProps || !(k in RESET)) continue; patchProps[k] = RESET[k]; any = true; }
const oldText = textOf(oldVnode), newText = textOf(newVnode); if (newText !== null && newText !== oldText) { patchProps.text = newText; any = true; }
else if (newText === null && oldText !== null) { patchProps.text = RESET.text; any = true; } if (any) inst.w.set(patchProps); } function eq(a, b) {
if (Object.is(a, b)) return true; if (Array.isArray(a) && Array.isArray(b)) { if (a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } return false; } function compatible(inst, vnode) {
if (isText(vnode)) return inst.kind === "host" && inst.autoLabel; if (vnode.key !== inst.key) return false;
if (typeof vnode.type === "function") return inst.kind === "comp" && inst.fn === vnode.type; if (inst.kind !== "host" || inst.tag !== vnode.type || inst.autoLabel) return false;
if (FIXED_ORDER[vnode.type]) return sameTabs(inst.vnode.kids, vnode.kids); if (inst.tag === "tab") return String(inst.vnode.props.name || "") === String(vnode.props.name || "");
return true; } function sameTabs(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) { const x = a[i], y = b[i];
if (isText(x) || isText(y) || x.type !== y.type) return false; if (x.type === "tab" && String(x.props.name || "") !== String(y.props.name || "")) return false; } return true; }
function patch(inst, vnode) { if (isText(vnode)) vnode = h("label", { text: String(vnode) }); if (inst.kind === "comp") { inst.vnode = vnode; inst.dirty = false;
renderComponent(inst); return inst; } const oldVnode = inst.vnode; inst.vnode = vnode; diffProps(inst, oldVnode, vnode); updateEvents(inst, vnode.props);
if (oldVnode.props.ref !== vnode.props.ref) { setRef(oldVnode.props.ref, null); setRef(vnode.props.ref, inst.w); } if (textOf(vnode) === null) diffKids(inst, vnode.kids);
return inst; } function diffKids(ownerInst, newKids) { const old = ownerInst.kids; const box = ownerInst.kind === "host" ? ownerInst.w : ownerInst.box;
const owner = ownerInst.kind === "host" ? ownerInst : ownerInst.owner; const keyed = old.some(i => i.key !== null) || newKids.some(v => !isText(v) && v.key !== null);
const next = []; let structural = false; if (!keyed) { for (let i = 0; i < newKids.length; i++) { const o = old[i]; if (o && compatible(o, newKids[i])) {
next.push(patch(o, newKids[i])); } else { if (o) unmount(o); next.push(mount(newKids[i], box, owner)); structural = true; } }
for (let i = newKids.length; i < old.length; i++) { unmount(old[i]); structural = true; } } else { const pool = new Map(); for (const o of old) { if (o.key === null) continue;
const type = tagOf(o); let byKey = pool.get(type); if (!byKey) pool.set(type, byKey = new Map()); byKey.set(o.key, o); } const reused = new Set(); let unkeyedAt = 0;
for (const v of newKids) { const key = isText(v) ? null : v.key; let o = null; if (key !== null) { const byKey = pool.get(typeOf(v)); o = (byKey && byKey.get(key)) || null;
} else { while (unkeyedAt < old.length && old[unkeyedAt].key !== null) unkeyedAt++; o = old[unkeyedAt] || null; unkeyedAt++; } if (o && !reused.has(o) && compatible(o, v)) {
reused.add(o); next.push(patch(o, v)); } else { next.push(mount(v, box, owner)); structural = true; } } for (const o of old) {
if (!reused.has(o)) { unmount(o); structural = true; } } if (!structural) { for (let i = 0; i < next.length; i++) { if (next[i] !== old[i]) { structural = true; break; } } } }
ownerInst.kids = next; if (structural && owner && !FIXED_ORDER[owner.tag]) reorder(owner, box); } function tagOf(inst) { return inst.kind === "comp" ? inst.fn : inst.tag; }
function typeOf(vnode) { return isText(vnode) ? "label" : vnode.type; } function reorder(owner, box) { const widgets = []; collect(owner, widgets, box);
for (let i = 0; i < widgets.length; i++) { if (widgets[i].index() !== i) widgets[i].index(i); } } function collect(inst, out, box) { for (const k of inst.kids) {
if (k.kind === "host") { if (k.box === box) out.push(k.w); } else { collect(k, out, box); } } } function render(tree, parent) { const box = parent || lv.screen(); box.clean();
const root = { kind: "frag", key: null, vnode: null, kids: [], box, owner: null, gone: false }; root.owner = root; root.kids = mountKids(flatten(tree), box, root);
reorder(root, box); runEffects(); return { update(next) { diffKids(root, flatten(next)); runEffects(); }, unmount() { for (const k of root.kids) unmount(k); root.kids = []; }, }; }
const UI = { h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval };
return UI; })();
__app();
