// GENERATED by tools/build-app.mjs from app/src/weather.jsx — do not edit.
// Edit the source and rebuild:  node tools/build-app.mjs weather
function __app() {   // line 4 here is line 1 of the .jsx
// weather.jsx — one glanceable screen, deliberately the opposite of the tabbed
// dashboard: no navigation, no chrome, one number you can read across a room.
//
// Shows what the whole stack is for. Config comes off the card, the reading
// comes over the network, and the last good value is cached so the screen says
// something useful the moment it opens, before any request finishes.
//
// Location comes from /config/weather.json:
//   { "name": "Philadelphia, PA", "lat": 39.95, "lon": -75.17 }
//
// The imperative original held four label handles and a render(data, source)
// function that wrote all four on every update — a re-render, written by hand.
// The one thing worth watching in the port is the retry timer: the original
// creates it when the radio is down and stops it when the radio comes up,
// tracked through a `waitingForWifi` variable that is nulled in two places.
// Here it is `useInterval(update, connected ? null : RETRY_MS)`, and the
// lifetime falls out of the condition.

const CONFIG = "/config/weather.json";
const CACHE = "/cache/weather.json";
const REFRESH_MS = 10 * 60 * 1000;
// The radio is usually still associating when this script starts — more so on a
// board pinned to it, which reaches the first update seconds after power-on. So
// "not connected" at boot means "not yet", and is worth asking about again
// shortly rather than sitting on a stale screen for a full refresh interval.
const RETRY_MS = 3000;

const place = (() => {
  const fallback = { name: "Philadelphia, PA", lat: 39.95, lon: -75.17 };
  try {
    const raw = fs.available() && fs.read(CONFIG);
    return raw ? Object.assign(fallback, JSON.parse(raw)) : fallback;
  } catch (e) {
    console.log("weather: bad config, using default —", e.message);
    return fallback;
  }
})();

// WMO codes, condensed to what fits on one line.
const CONDITIONS = {
  0: "Clear", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
  45: "Fog", 48: "Rime fog", 51: "Light drizzle", 53: "Drizzle", 55: "Heavy drizzle",
  61: "Light rain", 63: "Rain", 65: "Heavy rain", 66: "Freezing rain", 67: "Freezing rain",
  71: "Light snow", 73: "Snow", 75: "Heavy snow", 77: "Snow grains",
  80: "Showers", 81: "Showers", 82: "Violent showers",
  85: "Snow showers", 86: "Snow showers", 95: "Thunderstorm",
  96: "Thunderstorm", 99: "Thunderstorm",
};

// The status line's text and colour travel together, so they are one value
// rather than two that have to be kept in step.
const STATE = {
  live:     ["live",     "#4CAF50"],
  cached:   ["cached",   "#8A6D3B"],
  updating: ["updating", "#5A7285"],
  offline:  ["offline",  "#FF8A65"],
  failed:   ["failed",   "#FF5252"],
  blank:    ["",         "#5A7285"],
};

function readCache() {
  try {
    const raw = fs.available() && fs.read(CACHE);
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    // A corrupt cache is not worth failing over; the fetch will replace it.
    return null;
  }
}

function writeCache(data) {
  if (!fs.available()) return;
  if (!fs.isDir("/cache")) fs.mkdir("/cache");
  fs.write(CACHE, JSON.stringify(data));
}

function Weather() {
  // Whatever we knew last time is the first thing on screen, before any request
  // finishes — the same reason the original called showCached() first.
  const [data, setData] = useState(readCache);
  const [status, setStatus] = useState(() => (readCache() ? "cached" : "blank"));
  const [online, setOnline] = useState(true);
  const lastUpdate = useRef(0);

  const update = async () => {
    if (!wifi.status().connected) {
      setOnline(false);
      setStatus("offline");
      return;
    }
    setOnline(true);
    setStatus("updating");

    const url = `https://api.open-meteo.com/v1/forecast?latitude=${place.lat}` +
                `&longitude=${place.lon}&current=temperature_2m,weather_code,wind_speed_10m`;
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`http ${res.status}`);
      const cur = JSON.parse(res.body).current;
      const fresh = { temp: cur.temperature_2m, code: cur.weather_code, wind: cur.wind_speed_10m };
      setData(fresh);
      setStatus("live");
      writeCache(fresh);
      lastUpdate.current = sys.uptime();
    } catch (e) {
      console.log("weather: update failed —", e.message);
      setStatus("failed");
    }
  };

  useEffect(() => { update(); }, []);
  useInterval(update, REFRESH_MS);
  // The retry loop only exists while the radio is down. Passing null for the
  // interval is what stops it, so there is no timer handle to null out and no
  // second place that has to remember to.
  useInterval(update, online ? null : RETRY_MS);

  // Tap anywhere to refresh. The screen is the render root rather than a node in
  // the tree, so this one binding stays imperative — the runtime does not own
  // the screen object, only its children.
  useEffect(() => {
    lv.screen().set({ clickable: true }).on("click", () => {
      if (sys.uptime() - lastUpdate.current > 5000) update();
    });
  }, []);

  const [label, colour] = STATE[status];

  // This screen is deliberately not sized from the panel: it is text at fixed
  // sizes, and the number is meant to be readable across a room, so it neither
  // shrinks to a fraction of a small screen nor grows past the largest font that
  // exists. Adapting is done with alignment instead — every element hangs off an
  // edge or the middle, so the slack on a bigger panel goes into the margins.
  // Nothing here is tappable except the screen itself, so the firmware's corner
  // button covers no control and needs no clearance.
  return (
    h(Fragment, {},
h("label", {align: "top-left", x: 12, y: 10, font: 16, color: "#7FA8C4", text: place.name}),
h("label", {align: "top-right", x: -12, y: 12, font: 14, color: colour, text: label}),







h("label", {align: "left-mid", x: 12, y: -28, font: 40, color: "#FFFFFF",
text: data ? `${Math.round(data.temp)}°` : "--°"}),
h("label", {align: "left-mid", x: 14, y: 16, font: 20, color: "#C8D8E4",
text: data ? (CONDITIONS[data.code] || `Code ${data.code}`) : ""}),
h("label", {align: "left-mid", x: 14, y: 42, font: 14, color: "#5A7285",
text: data ? `wind ${Math.round(data.wind)} km/h` : ""}))

  );
}

lv.screen().set({ bg: "#0E1A24", pad: 0, scroll: false });
render(h(Weather, {}));

console.log(`weather: ${place.name} (${place.lat}, ${place.lon})`);
}
const {h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval} = (function () {
const HOST_TAGS = ["obj", "button", "label", "slider", "switch", "arc", "list", "chart", "tabview", "textarea", "keyboard", "bar", "checkbox",
"roller", "dropdown", "spinner", "led"]; const PARENT_MADE = { row: "list", tab: "tabview" }; const FIXED_ORDER = { tabview: true };
const TEXT_PROP = { label: true, button: true, row: true, checkbox: true }; const EVENTS = { onClick: "click", onChange: "change", onPress: "press", onPressing: "pressing",
onLongPress: "longpress", onReady: "ready", onCancel: "cancel", }; const CREATE_ONLY = { seriesColor: true, name: true };
const RESET = { hidden: false, text: "", scroll: true, clickable: true }; const NOT_A_PROP = { key: true, ref: true, children: true }; function h(type, props, ...kids) {
const p = {}; for (const k in props) p[k] = props[k]; if (kids.length) p.children = kids.length === 1 ? kids[0] : kids; return { type,
key: p.key === undefined || p.key === null ? null : String(p.key), props: p, kids: flatten(p.children), }; } function Fragment(props) { return props.children; }
function flatten(kids, out) { out = out || []; if (kids === undefined || kids === null || kids === false || kids === true) return out; if (Array.isArray(kids)) {
for (const k of kids) flatten(k, out); return out; } out.push(kids); return out; } const isText = v => typeof v === "string" || typeof v === "number"; let current = null;
let hookAt = 0; function slot(init) { if (!current) throw new Error("hooks can only be called while a component renders"); const hooks = current.hooks;
if (hooks.length <= hookAt) hooks.push(init()); return hooks[hookAt++]; } function useState(initial) { const inst = current; const cell = slot(() => {
const c = { v: typeof initial === "function" ? initial() : initial }; c.set = next => { const v = typeof next === "function" ? next(c.v) : next; if (Object.is(v, c.v)) return;
c.v = v; invalidate(inst); }; return c; }); return [cell.v, cell.set]; } function useRef(initial) { return slot(() => ({ current: initial })); } function useMemo(fn, deps) {
const s = slot(() => ({ deps: null, v: undefined, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.v = fn(); s.deps = deps; s.first = false; } return s.v; }
function useCallback(fn, deps) { return useMemo(() => fn, deps); } function useEffect(fn, deps) { const inst = current;
const s = slot(() => ({ deps: null, cleanup: null, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.deps = deps; s.first = false; inst.pending.push(s, fn); } }
function useInterval(fn, ms) { const held = useRef(fn); held.current = fn; useEffect(() => { if (ms === null || ms === undefined || ms === false) return undefined;
const t = lv.timer(ms, () => held.current()); return () => t.stop(); }, [ms]); } function sameDeps(a, b) { if (!a || !b || a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } const dirty = []; const effectQueue = []; let scheduled = false; let chain = 0;
function invalidate(inst) { if (inst.gone || inst.dirty) return; inst.dirty = true; dirty.push(inst); schedule(); } function schedule() { if (scheduled) return; scheduled = true;
Promise.resolve().then(flush); } function flush() { scheduled = false; if (++chain > 40) { chain = 0; dirty.length = 0; effectQueue.length = 0;
console.error("[ui] runaway render: a component sets state on every render, stopping"); return; } while (dirty.length) { const inst = dirty.shift();
if (!inst.dirty || inst.gone) continue; inst.dirty = false; try { renderComponent(inst); } catch (e) {
console.error("[ui] <" + (inst.fn.name || "anonymous") + "> failed to render:", e); } } runEffects(); if (!scheduled) chain = 0; } function runEffects() {
while (effectQueue.length) { const inst = effectQueue.shift(); const pending = inst.pending; inst.pending = []; for (let i = 0; i < pending.length; i += 2) { if (inst.gone) break;
const s = pending[i], fn = pending[i + 1]; if (s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } const r = safely(fn, "effect");
s.cleanup = typeof r === "function" ? r : null; } } } function safely(fn, what) { try { return fn(); } catch (e) { console.error("[ui] " + what + " threw:", e); return null; } }
function mount(vnode, box, owner) { if (isText(vnode)) { const inst = mountHost(h("label", { text: String(vnode) }), box, owner); inst.autoLabel = true; return inst; }
if (typeof vnode.type === "function") { const inst = { kind: "comp", vnode, fn: vnode.type, key: vnode.key, hooks: [],
pending: [], kids: [], box, owner, dirty: false, mounted: false, gone: false }; renderComponent(inst); return inst; } return mountHost(vnode, box, owner); }
function mountHost(vnode, box, owner) { const tag = vnode.type; const props = vnode.props; const inst = { kind: "host", vnode, key: vnode.key, tag, box, owner,
kids: [], handlers: {}, bound: {}, autoLabel: false, gone: false }; const create = {}; for (const k in props) { if (NOT_A_PROP[k] || EVENTS[k]) continue; create[k] = props[k]; }
const text = textOf(vnode); if (text !== null) create.text = text; if (PARENT_MADE[tag]) { if (!owner || owner.tag !== PARENT_MADE[tag])
throw new Error("<" + tag + "> must be a direct child of <" + PARENT_MADE[tag] + ">"); if (tag === "row") { inst.w = owner.w.add(create.text || ""); delete create.text; } else {
inst.w = owner.w.addTab(String(props.name || "")); delete create.name; } if (Object.keys(create).length) inst.w.set(create); } else {
if (HOST_TAGS.indexOf(tag) < 0) throw new Error("unknown element <" + tag + ">"); inst.w = lv[tag](box, create); } bindEvents(inst, props); setRef(props.ref, inst.w);
if (text === null) inst.kids = mountKids(vnode.kids, inst.w, inst); return inst; } function mountKids(kids, box, owner) { const out = [];
for (const k of kids) out.push(mount(k, box, owner)); return out; } function renderComponent(inst) { const prevInst = current, prevHook = hookAt; current = inst; hookAt = 0;
let out; try { out = inst.fn(inst.vnode.props); } finally { current = prevInst; hookAt = prevHook; } const kids = flatten(out); if (inst.mounted) { diffKids(inst, kids); } else {
inst.mounted = true; inst.kids = mountKids(kids, inst.box, inst.owner); } if (inst.pending.length) effectQueue.push(inst); } function unmount(inst) { inst.gone = true;
if (inst.kind === "comp") { for (const s of inst.hooks) { if (s && s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } } inst.pending.length = 0; }
for (const k of inst.kids) unmount(k); if (inst.kind === "host") { setRef(inst.vnode.props.ref, null); inst.w.delete(); } } function setRef(ref, value) { if (!ref) return;
if (typeof ref === "function") safely(() => ref(value), "ref"); else ref.current = value; } function bindEvents(inst, props) { for (const prop in EVENTS) {
if (typeof props[prop] !== "function") continue; inst.handlers[prop] = props[prop]; if (inst.bound[prop]) continue; inst.bound[prop] = true; const name = EVENTS[prop];
inst.w.on(name, (w, x, y) => { const fn = inst.handlers[prop]; if (!fn) return; const e = { target: w, type: name, x, y }; if (name === "change") e.value = w.value(); fn(e); }); }
} function updateEvents(inst, props) { for (const prop in EVENTS) { const fn = props[prop]; inst.handlers[prop] = typeof fn === "function" ? fn : null; } bindEvents(inst, props); }
function textOf(vnode) { if (!TEXT_PROP[vnode.type]) return null; if (vnode.props.text !== undefined) return String(vnode.props.text); if (!vnode.kids.length) return null;
if (!vnode.kids.every(isText)) return null; return vnode.kids.join(""); } function diffProps(inst, oldVnode, newVnode) { const oldProps = oldVnode.props, newProps = newVnode.props;
const patchProps = {}; let any = false; for (const k in newProps) { if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue;
if (!eq(newProps[k], oldProps[k])) { patchProps[k] = newProps[k]; any = true; } } for (const k in oldProps) {
if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue; if (k in newProps || !(k in RESET)) continue; patchProps[k] = RESET[k]; any = true; }
const oldText = textOf(oldVnode), newText = textOf(newVnode); if (newText !== null && newText !== oldText) { patchProps.text = newText; any = true; }
else if (newText === null && oldText !== null) { patchProps.text = RESET.text; any = true; } if (any) inst.w.set(patchProps); } function eq(a, b) {
if (Object.is(a, b)) return true; if (Array.isArray(a) && Array.isArray(b)) { if (a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } return false; } function compatible(inst, vnode) {
if (isText(vnode)) return inst.kind === "host" && inst.autoLabel; if (vnode.key !== inst.key) return false;
if (typeof vnode.type === "function") return inst.kind === "comp" && inst.fn === vnode.type; if (inst.kind !== "host" || inst.tag !== vnode.type || inst.autoLabel) return false;
if (FIXED_ORDER[vnode.type]) return sameTabs(inst.vnode.kids, vnode.kids); if (inst.tag === "tab") return String(inst.vnode.props.name || "") === String(vnode.props.name || "");
return true; } function sameTabs(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) { const x = a[i], y = b[i];
if (isText(x) || isText(y) || x.type !== y.type) return false; if (x.type === "tab" && String(x.props.name || "") !== String(y.props.name || "")) return false; } return true; }
function patch(inst, vnode) { if (isText(vnode)) vnode = h("label", { text: String(vnode) }); if (inst.kind === "comp") { inst.vnode = vnode; inst.dirty = false;
renderComponent(inst); return inst; } const oldVnode = inst.vnode; inst.vnode = vnode; diffProps(inst, oldVnode, vnode); updateEvents(inst, vnode.props);
if (oldVnode.props.ref !== vnode.props.ref) { setRef(oldVnode.props.ref, null); setRef(vnode.props.ref, inst.w); } if (textOf(vnode) === null) diffKids(inst, vnode.kids);
return inst; } function diffKids(ownerInst, newKids) { const old = ownerInst.kids; const box = ownerInst.kind === "host" ? ownerInst.w : ownerInst.box;
const owner = ownerInst.kind === "host" ? ownerInst : ownerInst.owner; const keyed = old.some(i => i.key !== null) || newKids.some(v => !isText(v) && v.key !== null);
const next = []; let structural = false; if (!keyed) { for (let i = 0; i < newKids.length; i++) { const o = old[i]; if (o && compatible(o, newKids[i])) {
next.push(patch(o, newKids[i])); } else { if (o) unmount(o); next.push(mount(newKids[i], box, owner)); structural = true; } }
for (let i = newKids.length; i < old.length; i++) { unmount(old[i]); structural = true; } } else { const pool = new Map(); for (const o of old) { if (o.key === null) continue;
const type = tagOf(o); let byKey = pool.get(type); if (!byKey) pool.set(type, byKey = new Map()); byKey.set(o.key, o); } const reused = new Set(); let unkeyedAt = 0;
for (const v of newKids) { const key = isText(v) ? null : v.key; let o = null; if (key !== null) { const byKey = pool.get(typeOf(v)); o = (byKey && byKey.get(key)) || null;
} else { while (unkeyedAt < old.length && old[unkeyedAt].key !== null) unkeyedAt++; o = old[unkeyedAt] || null; unkeyedAt++; } if (o && !reused.has(o) && compatible(o, v)) {
reused.add(o); next.push(patch(o, v)); } else { next.push(mount(v, box, owner)); structural = true; } } for (const o of old) {
if (!reused.has(o)) { unmount(o); structural = true; } } if (!structural) { for (let i = 0; i < next.length; i++) { if (next[i] !== old[i]) { structural = true; break; } } } }
ownerInst.kids = next; if (structural && owner && !FIXED_ORDER[owner.tag]) reorder(owner, box); } function tagOf(inst) { return inst.kind === "comp" ? inst.fn : inst.tag; }
function typeOf(vnode) { return isText(vnode) ? "label" : vnode.type; } function reorder(owner, box) { const widgets = []; collect(owner, widgets, box);
for (let i = 0; i < widgets.length; i++) { if (widgets[i].index() !== i) widgets[i].index(i); } } function collect(inst, out, box) { for (const k of inst.kids) {
if (k.kind === "host") { if (k.box === box) out.push(k.w); } else { collect(k, out, box); } } } function render(tree, parent) { const box = parent || lv.screen(); box.clean();
const root = { kind: "frag", key: null, vnode: null, kids: [], box, owner: null, gone: false }; root.owner = root; root.kids = mountKids(flatten(tree), box, root);
reorder(root, box); runEffects(); return { update(next) { diffKids(root, flatten(next)); runEffects(); }, unmount() { for (const k of root.kids) unmount(k); root.kids = []; }, }; }
const UI = { h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval };
return UI; })();
__app();
