// GENERATED by tools/build-app.mjs from app/src/wifi.jsx — do not edit.
// Edit the source and rebuild:  node tools/build-app.mjs wifi
function __app() {   // line 4 here is line 1 of the .jsx
// wifi.jsx — join a network from the touchscreen, no recompiling and no
// credentials in any file.
//
// Four screens: status, a scan list, a password prompt with the on-screen
// keyboard, and connecting. wifi.save() stores what you type in NVS, so the
// board rejoins by itself on every later boot. Nothing here can read the
// password back; the binding layer only accepts it.
//
// This is the app the component model was worth porting for, because three
// pieces of bookkeeping in the imperative original are gone rather than
// rewritten:
//
//   next(fn), the lv.timer(20) that moved a screen rebuild just past the end of
//   the click that asked for it. Used six times. A state write is already
//   deferred out of dispatch, so switching screens is now just setScreen().
//
//   reset(), which called scr.clean() and stopped whatever timer the outgoing
//   screen had left running. Unmounting does both: widgets go with the subtree,
//   and useInterval stops with its component.
//
//   screenTimer, the module-level handle that had to be nulled in three places
//   so a later stop() would not throw through a stale reference.

const S = lv.size();
// The firmware draws a 34px button in the bottom-right of every screen. Anything
// tappable that reaches into that corner is partly unreachable, so the keyboard,
// the buttons and the scan list all stop short of it.
const CORNER = 40;

function Header({ text }) {
  return h("label", {align: "top-left", x: 10, y: 8, font: 20, color: "#F0F4F8", text: text});
}

// ---------------------------------------------------------------- status

function Status({ go }) {
  // Buttons are decided once, from the state at mount; only the text above them
  // refreshes, so nothing moves under your finger. That is why this is its own
  // state rather than read from `st` below — a Forget button that appeared
  // mid-poll would shift the row as you reached for it.
  const [initial] = useState(() => wifi.status());
  const [st, setSt] = useState(initial);
  useInterval(() => setSt(wifi.status()), 1500);

  const BTN_W = Math.min(150, ((S.w - CORNER - 30) / 2) | 0);

  let line1, line2;
  if (st.connected) {
    line1 = [st.ssid, "#4CAF50"];
    line2 = [`${st.ip}    ${st.rssi} dBm`, "#8A9BAB"];
  } else if (st.saved && st.error) {
    // The case that had you guessing: credentials are stored but wrong. Say
    // which, and say what to do about it.
    line1 = [st.error, "#FF5252"];
    line2 = [st.error === "wrong password"
               ? "Tap Forget, then Scan to retype it."
               : `Retrying (${st.attempts})... or Forget and pick again.`,
             "#C8D8E4"];
  } else if (st.saved) {
    line1 = ["Connecting...", "#FFB74D"];
    line2 = ["", "#8A9BAB"];
  } else {
    line1 = ["Not set up", "#8A9BAB"];
    line2 = ["Tap Scan to choose a network.", "#64798C"];
  }

  return (
    h(Fragment, {},
h(Header, {text: "Wi-Fi"}),
h("label", {align: "top-left", x: 10, y: 40, font: 16, text: line1[0], color: line1[1]}),
h("label", {align: "top-left", x: 10, y: 64, font: 14, color: line2[1], text: line2[0]}),

h("button", {w: BTN_W, h: 36, align: "bottom-left", x: 10, y: -10, text: "Scan",
onClick: () => go({ name: "scan" })}),
initial.saved && (
        h("button", {w: BTN_W, h: 36, align: "bottom-left", x: 20 + BTN_W, y: -10, text: "Forget",
onClick: () => { wifi.forget(); go({ name: "status" }); }})
      ))

  );
}

// ---------------------------------------------------------------- scan list

function Scan({ go }) {
  const [rows, setRows] = useState(null);   // null while scanning
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    wifi.scan(nets => {
      if (!nets) { setFailed(true); return; }
      // Strongest first, and skip the unnamed ones a scan usually turns up.
      const seen = new Set();
      setRows(nets.filter(n => n.ssid && !seen.has(n.ssid) && seen.add(n.ssid))
                  .sort((a, b) => b.rssi - a.rssi));
    });
  }, []);

  const note = failed ? "scan failed" : rows ? `${rows.length} found` : "scanning...";

  return (
    h(Fragment, {},
h(Header, {text: "Choose a network"}),
h("label", {align: "top-right", x: -12, y: 14, font: 14, color: "#64798C", text: note}),




h("list", {w: S.w - CORNER - 10, h: S.h - 44, align: "bottom-left", x: 10, y: -5,
bg: "#101E2C", border: 0, radius: 8},
(rows || []).map(n => (
          h("row", {key: n.ssid,
text: `${n.ssid}   ${n.rssi > -60 ? "|||" : n.rssi > -75 ? "||" : "|"}${n.open ? "" : " *"}`,
onClick: () => go(n.open ? { name: "connecting", ssid: n.ssid, password: "" }
                                        : { name: "password", ssid: n.ssid })})
        )))
)

  );
}

// ---------------------------------------------------------------- password

function Password({ ssid, go }) {
  const [masked, setMasked] = useState(true);
  const field = useRef(null);
  const keyboard = useRef(null);

  // Routing the keyboard at a field is a call, not a prop — LVGL wires the key
  // handling internally and a script never sees a keystroke. Both widgets exist
  // by the time an effect runs, which is exactly what effects are for.
  useEffect(() => { keyboard.current.target(field.current); }, []);

  // The field takes the row, less the reveal button beside it.
  const REVEAL_W = 60;

  return (
    h(Fragment, {},
h("label", {align: "top-left", x: 10, y: 4, font: 16, color: "#F0F4F8", text: ssid}),
h("textarea", {ref: field,
w: S.w - REVEAL_W - 20, h: 34, align: "top-left", x: 10, y: 26,
placeholder: "password", password: masked, oneLine: true, maxLength: 63}),




h("button", {w: REVEAL_W, h: 34, align: "top-right", x: -10, y: 26,
text: masked ? "Show" : "Hide", onClick: () => setMasked(!masked)}),



h("keyboard", {ref: keyboard, w: S.w - CORNER, h: S.h - 68, align: "bottom-left", x: 0, y: 0,
onReady: () => go({ name: "connecting", ssid, password: field.current.value() }),
onCancel: () => go({ name: "scan" })}))

  );
}

// ---------------------------------------------------------------- connecting

function Connecting({ ssid, password, go }) {
  const [waited, setWaited] = useState(0);
  const [failure, setFailure] = useState(null);   // null while still trying

  useEffect(() => { wifi.save(ssid, password); }, []);

  // Passing null for the interval is what stops the poll on a terminal result,
  // so there is no timer handle to stop and nothing to null out afterwards.
  useInterval(() => {
    const st = wifi.status();
    if (st.connected) {
      go({ name: "status" });
    } else if (st.error === "wrong password") {
      // No point waiting out the timeout for something that will not improve.
      setFailure({ text: "Wrong password", retry: "password" });
    } else if (waited + 500 >= 15000) {
      setFailure({ text: st.error || "Could not connect", retry: "scan" });
    } else {
      setWaited(waited + 500);
    }
  }, failure ? null : 500);

  return (
    h(Fragment, {},
h(Header, {text: "Connecting"}),
h("label", {align: "center", font: 16,
color: failure ? "#FF5252" : "#8A9BAB",
text: failure ? failure.text : `${ssid}\n${waited / 1000}s`}),
failure && (
        h("button", {w: 150, h: 36, align: "bottom-mid", y: -10, text: "Try again",
onClick: () => go(failure.retry === "password"
                  ? { name: "password", ssid }
                  : { name: "scan" })})
      ))

  );
}

// ---------------------------------------------------------------- the app

function Wifi() {
  const [screen, setScreen] = useState({ name: "status" });

  // Switching screens from inside a click handler, with no deferral: the render
  // this schedules cannot run until lv_timer_handler() has returned, so the
  // widget being dispatched to is still alive for the rest of the event.
  const go = setScreen;

  if (screen.name === "scan") return h(Scan, {go: go});
  if (screen.name === "password") return h(Password, {ssid: screen.ssid, go: go});
  if (screen.name === "connecting") {
    return h(Connecting, {ssid: screen.ssid, password: screen.password, go: go});
  }
  return h(Status, {go: go});
}

lv.screen().set({ bg: "#0B1622", pad: 0, scroll: false });
render(h(Wifi, {}));

console.log("wifi: setup app ready");
}
const {h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval} = (function () {
const HOST_TAGS = ["obj", "button", "label", "slider", "switch", "arc", "list", "chart", "tabview", "textarea", "keyboard", "bar", "checkbox",
"roller", "dropdown", "spinner", "led"]; const PARENT_MADE = { row: "list", tab: "tabview" }; const FIXED_ORDER = { tabview: true };
const TEXT_PROP = { label: true, button: true, row: true, checkbox: true }; const EVENTS = { onClick: "click", onChange: "change", onPress: "press", onPressing: "pressing",
onLongPress: "longpress", onReady: "ready", onCancel: "cancel", }; const CREATE_ONLY = { seriesColor: true, name: true };
const RESET = { hidden: false, text: "", scroll: true, clickable: true }; const NOT_A_PROP = { key: true, ref: true, children: true }; function h(type, props, ...kids) {
const p = {}; for (const k in props) p[k] = props[k]; if (kids.length) p.children = kids.length === 1 ? kids[0] : kids; return { type,
key: p.key === undefined || p.key === null ? null : String(p.key), props: p, kids: flatten(p.children), }; } function Fragment(props) { return props.children; }
function flatten(kids, out) { out = out || []; if (kids === undefined || kids === null || kids === false || kids === true) return out; if (Array.isArray(kids)) {
for (const k of kids) flatten(k, out); return out; } out.push(kids); return out; } const isText = v => typeof v === "string" || typeof v === "number"; let current = null;
let hookAt = 0; function slot(init) { if (!current) throw new Error("hooks can only be called while a component renders"); const hooks = current.hooks;
if (hooks.length <= hookAt) hooks.push(init()); return hooks[hookAt++]; } function useState(initial) { const inst = current; const cell = slot(() => {
const c = { v: typeof initial === "function" ? initial() : initial }; c.set = next => { const v = typeof next === "function" ? next(c.v) : next; if (Object.is(v, c.v)) return;
c.v = v; invalidate(inst); }; return c; }); return [cell.v, cell.set]; } function useRef(initial) { return slot(() => ({ current: initial })); } function useMemo(fn, deps) {
const s = slot(() => ({ deps: null, v: undefined, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.v = fn(); s.deps = deps; s.first = false; } return s.v; }
function useCallback(fn, deps) { return useMemo(() => fn, deps); } function useEffect(fn, deps) { const inst = current;
const s = slot(() => ({ deps: null, cleanup: null, first: true })); if (s.first || !sameDeps(s.deps, deps)) { s.deps = deps; s.first = false; inst.pending.push(s, fn); } }
function useInterval(fn, ms) { const held = useRef(fn); held.current = fn; useEffect(() => { if (ms === null || ms === undefined || ms === false) return undefined;
const t = lv.timer(ms, () => held.current()); return () => t.stop(); }, [ms]); } function sameDeps(a, b) { if (!a || !b || a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } const dirty = []; const effectQueue = []; let scheduled = false; let chain = 0;
function invalidate(inst) { if (inst.gone || inst.dirty) return; inst.dirty = true; dirty.push(inst); schedule(); } function schedule() { if (scheduled) return; scheduled = true;
Promise.resolve().then(flush); } function flush() { scheduled = false; if (++chain > 40) { chain = 0; dirty.length = 0; effectQueue.length = 0;
console.error("[ui] runaway render: a component sets state on every render, stopping"); return; } while (dirty.length) { const inst = dirty.shift();
if (!inst.dirty || inst.gone) continue; inst.dirty = false; try { renderComponent(inst); } catch (e) {
console.error("[ui] <" + (inst.fn.name || "anonymous") + "> failed to render:", e); } } runEffects(); if (!scheduled) chain = 0; } function runEffects() {
while (effectQueue.length) { const inst = effectQueue.shift(); const pending = inst.pending; inst.pending = []; for (let i = 0; i < pending.length; i += 2) { if (inst.gone) break;
const s = pending[i], fn = pending[i + 1]; if (s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } const r = safely(fn, "effect");
s.cleanup = typeof r === "function" ? r : null; } } } function safely(fn, what) { try { return fn(); } catch (e) { console.error("[ui] " + what + " threw:", e); return null; } }
function mount(vnode, box, owner) { if (isText(vnode)) { const inst = mountHost(h("label", { text: String(vnode) }), box, owner); inst.autoLabel = true; return inst; }
if (typeof vnode.type === "function") { const inst = { kind: "comp", vnode, fn: vnode.type, key: vnode.key, hooks: [],
pending: [], kids: [], box, owner, dirty: false, mounted: false, gone: false }; renderComponent(inst); return inst; } return mountHost(vnode, box, owner); }
function mountHost(vnode, box, owner) { const tag = vnode.type; const props = vnode.props; const inst = { kind: "host", vnode, key: vnode.key, tag, box, owner,
kids: [], handlers: {}, bound: {}, autoLabel: false, gone: false }; const create = {}; for (const k in props) { if (NOT_A_PROP[k] || EVENTS[k]) continue; create[k] = props[k]; }
const text = textOf(vnode); if (text !== null) create.text = text; if (PARENT_MADE[tag]) { if (!owner || owner.tag !== PARENT_MADE[tag])
throw new Error("<" + tag + "> must be a direct child of <" + PARENT_MADE[tag] + ">"); if (tag === "row") { inst.w = owner.w.add(create.text || ""); delete create.text; } else {
inst.w = owner.w.addTab(String(props.name || "")); delete create.name; } if (Object.keys(create).length) inst.w.set(create); } else {
if (HOST_TAGS.indexOf(tag) < 0) throw new Error("unknown element <" + tag + ">"); inst.w = lv[tag](box, create); } bindEvents(inst, props); setRef(props.ref, inst.w);
if (text === null) inst.kids = mountKids(vnode.kids, inst.w, inst); return inst; } function mountKids(kids, box, owner) { const out = [];
for (const k of kids) out.push(mount(k, box, owner)); return out; } function renderComponent(inst) { const prevInst = current, prevHook = hookAt; current = inst; hookAt = 0;
let out; try { out = inst.fn(inst.vnode.props); } finally { current = prevInst; hookAt = prevHook; } const kids = flatten(out); if (inst.mounted) { diffKids(inst, kids); } else {
inst.mounted = true; inst.kids = mountKids(kids, inst.box, inst.owner); } if (inst.pending.length) effectQueue.push(inst); } function unmount(inst) { inst.gone = true;
if (inst.kind === "comp") { for (const s of inst.hooks) { if (s && s.cleanup) { safely(s.cleanup, "effect cleanup"); s.cleanup = null; } } inst.pending.length = 0; }
for (const k of inst.kids) unmount(k); if (inst.kind === "host") { setRef(inst.vnode.props.ref, null); inst.w.delete(); } } function setRef(ref, value) { if (!ref) return;
if (typeof ref === "function") safely(() => ref(value), "ref"); else ref.current = value; } function bindEvents(inst, props) { for (const prop in EVENTS) {
if (typeof props[prop] !== "function") continue; inst.handlers[prop] = props[prop]; if (inst.bound[prop]) continue; inst.bound[prop] = true; const name = EVENTS[prop];
inst.w.on(name, (w, x, y) => { const fn = inst.handlers[prop]; if (!fn) return; const e = { target: w, type: name, x, y }; if (name === "change") e.value = w.value(); fn(e); }); }
} function updateEvents(inst, props) { for (const prop in EVENTS) { const fn = props[prop]; inst.handlers[prop] = typeof fn === "function" ? fn : null; } bindEvents(inst, props); }
function textOf(vnode) { if (!TEXT_PROP[vnode.type]) return null; if (vnode.props.text !== undefined) return String(vnode.props.text); if (!vnode.kids.length) return null;
if (!vnode.kids.every(isText)) return null; return vnode.kids.join(""); } function diffProps(inst, oldVnode, newVnode) { const oldProps = oldVnode.props, newProps = newVnode.props;
const patchProps = {}; let any = false; for (const k in newProps) { if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue;
if (!eq(newProps[k], oldProps[k])) { patchProps[k] = newProps[k]; any = true; } } for (const k in oldProps) {
if (NOT_A_PROP[k] || EVENTS[k] || CREATE_ONLY[k] || k === "text") continue; if (k in newProps || !(k in RESET)) continue; patchProps[k] = RESET[k]; any = true; }
const oldText = textOf(oldVnode), newText = textOf(newVnode); if (newText !== null && newText !== oldText) { patchProps.text = newText; any = true; }
else if (newText === null && oldText !== null) { patchProps.text = RESET.text; any = true; } if (any) inst.w.set(patchProps); } function eq(a, b) {
if (Object.is(a, b)) return true; if (Array.isArray(a) && Array.isArray(b)) { if (a.length !== b.length) return false;
for (let i = 0; i < a.length; i++) if (!Object.is(a[i], b[i])) return false; return true; } return false; } function compatible(inst, vnode) {
if (isText(vnode)) return inst.kind === "host" && inst.autoLabel; if (vnode.key !== inst.key) return false;
if (typeof vnode.type === "function") return inst.kind === "comp" && inst.fn === vnode.type; if (inst.kind !== "host" || inst.tag !== vnode.type || inst.autoLabel) return false;
if (FIXED_ORDER[vnode.type]) return sameTabs(inst.vnode.kids, vnode.kids); if (inst.tag === "tab") return String(inst.vnode.props.name || "") === String(vnode.props.name || "");
return true; } function sameTabs(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) { const x = a[i], y = b[i];
if (isText(x) || isText(y) || x.type !== y.type) return false; if (x.type === "tab" && String(x.props.name || "") !== String(y.props.name || "")) return false; } return true; }
function patch(inst, vnode) { if (isText(vnode)) vnode = h("label", { text: String(vnode) }); if (inst.kind === "comp") { inst.vnode = vnode; inst.dirty = false;
renderComponent(inst); return inst; } const oldVnode = inst.vnode; inst.vnode = vnode; diffProps(inst, oldVnode, vnode); updateEvents(inst, vnode.props);
if (oldVnode.props.ref !== vnode.props.ref) { setRef(oldVnode.props.ref, null); setRef(vnode.props.ref, inst.w); } if (textOf(vnode) === null) diffKids(inst, vnode.kids);
return inst; } function diffKids(ownerInst, newKids) { const old = ownerInst.kids; const box = ownerInst.kind === "host" ? ownerInst.w : ownerInst.box;
const owner = ownerInst.kind === "host" ? ownerInst : ownerInst.owner; const keyed = old.some(i => i.key !== null) || newKids.some(v => !isText(v) && v.key !== null);
const next = []; let structural = false; if (!keyed) { for (let i = 0; i < newKids.length; i++) { const o = old[i]; if (o && compatible(o, newKids[i])) {
next.push(patch(o, newKids[i])); } else { if (o) unmount(o); next.push(mount(newKids[i], box, owner)); structural = true; } }
for (let i = newKids.length; i < old.length; i++) { unmount(old[i]); structural = true; } } else { const pool = new Map(); for (const o of old) { if (o.key === null) continue;
const type = tagOf(o); let byKey = pool.get(type); if (!byKey) pool.set(type, byKey = new Map()); byKey.set(o.key, o); } const reused = new Set(); let unkeyedAt = 0;
for (const v of newKids) { const key = isText(v) ? null : v.key; let o = null; if (key !== null) { const byKey = pool.get(typeOf(v)); o = (byKey && byKey.get(key)) || null;
} else { while (unkeyedAt < old.length && old[unkeyedAt].key !== null) unkeyedAt++; o = old[unkeyedAt] || null; unkeyedAt++; } if (o && !reused.has(o) && compatible(o, v)) {
reused.add(o); next.push(patch(o, v)); } else { next.push(mount(v, box, owner)); structural = true; } } for (const o of old) {
if (!reused.has(o)) { unmount(o); structural = true; } } if (!structural) { for (let i = 0; i < next.length; i++) { if (next[i] !== old[i]) { structural = true; break; } } } }
ownerInst.kids = next; if (structural && owner && !FIXED_ORDER[owner.tag]) reorder(owner, box); } function tagOf(inst) { return inst.kind === "comp" ? inst.fn : inst.tag; }
function typeOf(vnode) { return isText(vnode) ? "label" : vnode.type; } function reorder(owner, box) { const widgets = []; collect(owner, widgets, box);
for (let i = 0; i < widgets.length; i++) { if (widgets[i].index() !== i) widgets[i].index(i); } } function collect(inst, out, box) { for (const k of inst.kids) {
if (k.kind === "host") { if (k.box === box) out.push(k.w); } else { collect(k, out, box); } } } function render(tree, parent) { const box = parent || lv.screen(); box.clean();
const root = { kind: "frag", key: null, vnode: null, kids: [], box, owner: null, gone: false }; root.owner = root; root.kids = mountKids(flatten(tree), box, root);
reorder(root, box); runEffects(); return { update(next) { diffKids(root, flatten(next)); runEffects(); }, unmount() { for (const k of root.kids) unmount(k); root.kids = []; }, }; }
const UI = { h, Fragment, render, useState, useEffect, useRef, useMemo, useCallback, useInterval };
return UI; })();
__app();
